CREATE OR REPLACE CORTEX SEARCH SERVICE DASH_DB_SI.RETAIL.SUPPORT_CASES
  ON TRANSCRIPT
  ATTRIBUTES TITLE, PRODUCT
  WAREHOUSE = DASH_WH_SI
  TARGET_LAG = '1 hour'
  AS (
    SELECT *
    FROM DASH_DB_SI.RETAIL.SUPPORT_CASES
  );